backend:
  name: git-gateway
  repo: https://github.com/laiscavalcanti/desertovermelho.com.br
  branch: main # Branch to update (optional; defaults to master)
  site_domain: https://desertovermelho.com.br

publish_mode: editorial_workflow
media_folder: static/assets/img
public_folder: static/assets/img

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    media_folder: "static/assets/img"
    public_folder: "static/assets/img"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Image Post", name: "imagePost", widget: "image" }
      - { label: "Author", name: "author", widget: "string" required: false}
      - { label: "Tag", name: "tags", widget: "list", default: ['']}
      - { label: "TemplateKey", name: "templateKey", widget: "string" }
      - { label: "Texto", name: "body", widget: "markdown" }